There are 5 ways to handle error

1. try catch 
============
function readingFileData(){
    try{
        let data = fs.readFileSync("file1.txt","utf-8");
        console.log(data);
    } catch(error){
        console.log("File not Found!!!");
    }
}

readingFileData()





2. handling with callback
=========================
function readingFile(){
   fs.readFile("file1.txt","utf-8",(err,data) => {
    if(err){
        console.log("File not found!!!!!");
    }

    else{
        console.log(data);
        
    }
   }) 
}

readingFile()





3. using promises
================
function readingFile(){
    return new Promise((reject,resolve) => {
        fs.readFile("file.txt","utf-8",(err,data) => {
            if(err){
                reject(err);
                return;
            }

            else{
                resolve(data);
            }
        });
    })
}

readingFile().then(data => console.log(data)).catch(error => console.log(error))




4. async await
==============
async function readingFile() {
  try {
    const info = await fs.readFileSync("fil1e.txt", "utf-8");
    console.log(info);
  } catch (err) {
    console.log(err);
  }
}

readingFile()